apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: insight-system
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: lechaukha12/java-otel-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_NAME
              value: "order-service"
            - name: PEER_URL
              value: "http://payment-service:8080"
            - name: OTEL_SERVICE_NAME
              value: "order-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://insight-api:8080"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: insight-system
spec:
  selector:
    app: order-service
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: insight-system
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: lechaukha12/java-otel-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_NAME
              value: "payment-service"
            - name: PEER_URL
              value: "http://order-service:8080"
            - name: OTEL_SERVICE_NAME
              value: "payment-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://insight-api:8080"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: insight-system
spec:
  selector:
    app: payment-service
  ports:
    - port: 8080
      targetPort: 8080
